// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package imap_pop3_tests.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;

public class SendEmail extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String to;
	private java.lang.String from;
	private java.lang.String host;
	private java.lang.Long port;
	private java.lang.String subject;
	private java.lang.String message;
	private IMendixObject __attachment;
	private system.proxies.FileDocument attachment;
	private imap_pop3_tests.proxies.ContentType contentType;
	private imap_pop3_tests.proxies.CharacterSet charSet;

	public SendEmail(IContext context, java.lang.String to, java.lang.String from, java.lang.String host, java.lang.Long port, java.lang.String subject, java.lang.String message, IMendixObject attachment, java.lang.String contentType, java.lang.String charSet)
	{
		super(context);
		this.to = to;
		this.from = from;
		this.host = host;
		this.port = port;
		this.subject = subject;
		this.message = message;
		this.__attachment = attachment;
		this.contentType = contentType == null ? null : imap_pop3_tests.proxies.ContentType.valueOf(contentType);
		this.charSet = charSet == null ? null : imap_pop3_tests.proxies.CharacterSet.valueOf(charSet);
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.attachment = __attachment == null ? null : system.proxies.FileDocument.initialize(getContext(), __attachment);

		// BEGIN USER CODE
		Properties properties = new Properties();
	    properties.setProperty("mail.smtp.host", host);
	    properties.setProperty("mail.smtp.port", port.toString());
	    Session session = Session.getDefaultInstance(properties);
        MimeMessage mimeMessage = new MimeMessage(session);
        mimeMessage.setFrom(new InternetAddress(from));
        mimeMessage.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
        mimeMessage.setSubject(subject);
        mimeMessage.setText(message);
        
        // todo: attachment, contentType, charSet
        
        Transport.send(mimeMessage);
        
        return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "SendEmail";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
