// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package imap_pop3_email.actions;

import imap_pop3_email.proxies.EmailMessage;
import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.webui.FeedbackHelper;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Retreives emails from the server.
 * The returned list contains all received emails.
 */
public class RetrieveEmailMessages extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __account;
	private imap_pop3_email.proxies.EmailAccount account;

	public RetrieveEmailMessages(IContext context, IMendixObject account)
	{
		super(context);
		this.__account = account;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.account = __account == null ? null : imap_pop3_email.proxies.EmailAccount.initialize(getContext(), __account);

		// BEGIN USER CODE
		EmailHandler handler = new EmailHandler(account, getContext());
		List<IMendixObject> result = handler.readEmailMessages();
		FeedbackHelper.addRefreshClass(getContext(), EmailMessage.entityName);
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RetrieveEmailMessages";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
