// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package imap_pop3_tests.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the IMAP_POP3_Tests module

	public static java.lang.String getHost()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("IMAP_POP3_Tests.Host");
	}

	public static java.lang.String getPassword()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("IMAP_POP3_Tests.Password");
	}

	public static java.lang.String getUsername()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("IMAP_POP3_Tests.Username");
	}
}