// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package imap_pop3_email.proxies;

public class Attachment extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "IMAP_POP3_email.Attachment";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Position("Position"),
		ContentID("ContentID"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Attachment_EmailMessage("IMAP_POP3_email.Attachment_EmailMessage");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Attachment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "IMAP_POP3_email.Attachment"));
	}

	protected Attachment(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject attachmentMendixObject)
	{
		super(context, attachmentMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("IMAP_POP3_email.Attachment", attachmentMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a IMAP_POP3_email.Attachment");
	}

	/**
	 * @deprecated Use 'Attachment.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static imap_pop3_email.proxies.Attachment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return imap_pop3_email.proxies.Attachment.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static imap_pop3_email.proxies.Attachment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new imap_pop3_email.proxies.Attachment(context, mendixObject);
	}

	public static imap_pop3_email.proxies.Attachment load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return imap_pop3_email.proxies.Attachment.initialize(context, mendixObject);
	}

	public static java.util.List<imap_pop3_email.proxies.Attachment> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<imap_pop3_email.proxies.Attachment> result = new java.util.ArrayList<imap_pop3_email.proxies.Attachment>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//IMAP_POP3_email.Attachment" + xpathConstraint))
			result.add(imap_pop3_email.proxies.Attachment.initialize(context, obj));
		return result;
	}

	/**
	 * Set value of Position
	 * @param position
	 */
	public final imap_pop3_email.proxies.AttachmentPosition getPosition()
	{
		return getPosition(getContext());
	}

	/**
	 * @param context
	 * @return value of Position
	 */
	public final imap_pop3_email.proxies.AttachmentPosition getPosition(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Position.toString());
		if (obj == null)
			return null;

		return imap_pop3_email.proxies.AttachmentPosition.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Position
	 * @param position
	 */
	public final void setPosition(imap_pop3_email.proxies.AttachmentPosition position)
	{
		setPosition(getContext(), position);
	}

	/**
	 * Set value of Position
	 * @param context
	 * @param position
	 */
	public final void setPosition(com.mendix.systemwideinterfaces.core.IContext context, imap_pop3_email.proxies.AttachmentPosition position)
	{
		if (position != null)
			getMendixObject().setValue(context, MemberNames.Position.toString(), position.toString());
		else
			getMendixObject().setValue(context, MemberNames.Position.toString(), null);
	}

	/**
	 * @return value of ContentID
	 */
	public final java.lang.String getContentID()
	{
		return getContentID(getContext());
	}

	/**
	 * @param context
	 * @return value of ContentID
	 */
	public final java.lang.String getContentID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContentID.toString());
	}

	/**
	 * Set value of ContentID
	 * @param contentid
	 */
	public final void setContentID(java.lang.String contentid)
	{
		setContentID(getContext(), contentid);
	}

	/**
	 * Set value of ContentID
	 * @param context
	 * @param contentid
	 */
	public final void setContentID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String contentid)
	{
		getMendixObject().setValue(context, MemberNames.ContentID.toString(), contentid);
	}

	/**
	 * @return value of Attachment_EmailMessage
	 */
	public final imap_pop3_email.proxies.EmailMessage getAttachment_EmailMessage() throws com.mendix.core.CoreException
	{
		return getAttachment_EmailMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of Attachment_EmailMessage
	 */
	public final imap_pop3_email.proxies.EmailMessage getAttachment_EmailMessage(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		imap_pop3_email.proxies.EmailMessage result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Attachment_EmailMessage.toString());
		if (identifier != null)
			result = imap_pop3_email.proxies.EmailMessage.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Attachment_EmailMessage
	 * @param attachment_emailmessage
	 */
	public final void setAttachment_EmailMessage(imap_pop3_email.proxies.EmailMessage attachment_emailmessage)
	{
		setAttachment_EmailMessage(getContext(), attachment_emailmessage);
	}

	/**
	 * Set value of Attachment_EmailMessage
	 * @param context
	 * @param attachment_emailmessage
	 */
	public final void setAttachment_EmailMessage(com.mendix.systemwideinterfaces.core.IContext context, imap_pop3_email.proxies.EmailMessage attachment_emailmessage)
	{
		if (attachment_emailmessage == null)
			getMendixObject().setValue(context, MemberNames.Attachment_EmailMessage.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Attachment_EmailMessage.toString(), attachment_emailmessage.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final imap_pop3_email.proxies.Attachment that = (imap_pop3_email.proxies.Attachment) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "IMAP_POP3_email.Attachment";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
