// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package imap_pop3_email.proxies;

public class EmailMessage
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject emailMessageMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "IMAP_POP3_email.EmailMessage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Subject("Subject"),
		Senddate("Senddate"),
		RetrieveDate("RetrieveDate"),
		From("From"),
		To("To"),
		CC("CC"),
		BCC("BCC"),
		Content("Content"),
		isHTML("isHTML"),
		hasAttachments("hasAttachments"),
		AttachmentAmount("AttachmentAmount"),
		Size("Size"),
		EmailMessage_EmailAccount("IMAP_POP3_email.EmailMessage_EmailAccount");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EmailMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "IMAP_POP3_email.EmailMessage"));
	}

	protected EmailMessage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject emailMessageMendixObject)
	{
		if (emailMessageMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("IMAP_POP3_email.EmailMessage", emailMessageMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a IMAP_POP3_email.EmailMessage");

		this.emailMessageMendixObject = emailMessageMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'EmailMessage.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static imap_pop3_email.proxies.EmailMessage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return imap_pop3_email.proxies.EmailMessage.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static imap_pop3_email.proxies.EmailMessage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new imap_pop3_email.proxies.EmailMessage(context, mendixObject);
	}

	public static imap_pop3_email.proxies.EmailMessage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return imap_pop3_email.proxies.EmailMessage.initialize(context, mendixObject);
	}

	public static java.util.List<imap_pop3_email.proxies.EmailMessage> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<imap_pop3_email.proxies.EmailMessage> result = new java.util.ArrayList<imap_pop3_email.proxies.EmailMessage>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//IMAP_POP3_email.EmailMessage" + xpathConstraint))
			result.add(imap_pop3_email.proxies.EmailMessage.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Subject
	 */
	public final java.lang.String getSubject()
	{
		return getSubject(getContext());
	}

	/**
	 * @param context
	 * @return value of Subject
	 */
	public final java.lang.String getSubject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Subject.toString());
	}

	/**
	 * Set value of Subject
	 * @param subject
	 */
	public final void setSubject(java.lang.String subject)
	{
		setSubject(getContext(), subject);
	}

	/**
	 * Set value of Subject
	 * @param context
	 * @param subject
	 */
	public final void setSubject(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subject)
	{
		getMendixObject().setValue(context, MemberNames.Subject.toString(), subject);
	}

	/**
	 * @return value of Senddate
	 */
	public final java.util.Date getSenddate()
	{
		return getSenddate(getContext());
	}

	/**
	 * @param context
	 * @return value of Senddate
	 */
	public final java.util.Date getSenddate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Senddate.toString());
	}

	/**
	 * Set value of Senddate
	 * @param senddate
	 */
	public final void setSenddate(java.util.Date senddate)
	{
		setSenddate(getContext(), senddate);
	}

	/**
	 * Set value of Senddate
	 * @param context
	 * @param senddate
	 */
	public final void setSenddate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date senddate)
	{
		getMendixObject().setValue(context, MemberNames.Senddate.toString(), senddate);
	}

	/**
	 * @return value of RetrieveDate
	 */
	public final java.util.Date getRetrieveDate()
	{
		return getRetrieveDate(getContext());
	}

	/**
	 * @param context
	 * @return value of RetrieveDate
	 */
	public final java.util.Date getRetrieveDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.RetrieveDate.toString());
	}

	/**
	 * Set value of RetrieveDate
	 * @param retrievedate
	 */
	public final void setRetrieveDate(java.util.Date retrievedate)
	{
		setRetrieveDate(getContext(), retrievedate);
	}

	/**
	 * Set value of RetrieveDate
	 * @param context
	 * @param retrievedate
	 */
	public final void setRetrieveDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date retrievedate)
	{
		getMendixObject().setValue(context, MemberNames.RetrieveDate.toString(), retrievedate);
	}

	/**
	 * @return value of From
	 */
	public final java.lang.String getFrom()
	{
		return getFrom(getContext());
	}

	/**
	 * @param context
	 * @return value of From
	 */
	public final java.lang.String getFrom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.From.toString());
	}

	/**
	 * Set value of From
	 * @param from
	 */
	public final void setFrom(java.lang.String from)
	{
		setFrom(getContext(), from);
	}

	/**
	 * Set value of From
	 * @param context
	 * @param from
	 */
	public final void setFrom(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String from)
	{
		getMendixObject().setValue(context, MemberNames.From.toString(), from);
	}

	/**
	 * @return value of To
	 */
	public final java.lang.String getTo()
	{
		return getTo(getContext());
	}

	/**
	 * @param context
	 * @return value of To
	 */
	public final java.lang.String getTo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.To.toString());
	}

	/**
	 * Set value of To
	 * @param to
	 */
	public final void setTo(java.lang.String to)
	{
		setTo(getContext(), to);
	}

	/**
	 * Set value of To
	 * @param context
	 * @param to
	 */
	public final void setTo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String to)
	{
		getMendixObject().setValue(context, MemberNames.To.toString(), to);
	}

	/**
	 * @return value of CC
	 */
	public final java.lang.String getCC()
	{
		return getCC(getContext());
	}

	/**
	 * @param context
	 * @return value of CC
	 */
	public final java.lang.String getCC(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CC.toString());
	}

	/**
	 * Set value of CC
	 * @param cc
	 */
	public final void setCC(java.lang.String cc)
	{
		setCC(getContext(), cc);
	}

	/**
	 * Set value of CC
	 * @param context
	 * @param cc
	 */
	public final void setCC(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cc)
	{
		getMendixObject().setValue(context, MemberNames.CC.toString(), cc);
	}

	/**
	 * @return value of BCC
	 */
	public final java.lang.String getBCC()
	{
		return getBCC(getContext());
	}

	/**
	 * @param context
	 * @return value of BCC
	 */
	public final java.lang.String getBCC(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BCC.toString());
	}

	/**
	 * Set value of BCC
	 * @param bcc
	 */
	public final void setBCC(java.lang.String bcc)
	{
		setBCC(getContext(), bcc);
	}

	/**
	 * Set value of BCC
	 * @param context
	 * @param bcc
	 */
	public final void setBCC(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bcc)
	{
		getMendixObject().setValue(context, MemberNames.BCC.toString(), bcc);
	}

	/**
	 * @return value of Content
	 */
	public final java.lang.String getContent()
	{
		return getContent(getContext());
	}

	/**
	 * @param context
	 * @return value of Content
	 */
	public final java.lang.String getContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Content.toString());
	}

	/**
	 * Set value of Content
	 * @param content
	 */
	public final void setContent(java.lang.String content)
	{
		setContent(getContext(), content);
	}

	/**
	 * Set value of Content
	 * @param context
	 * @param content
	 */
	public final void setContent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String content)
	{
		getMendixObject().setValue(context, MemberNames.Content.toString(), content);
	}

	/**
	 * @return value of isHTML
	 */
	public final java.lang.Boolean getisHTML()
	{
		return getisHTML(getContext());
	}

	/**
	 * @param context
	 * @return value of isHTML
	 */
	public final java.lang.Boolean getisHTML(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isHTML.toString());
	}

	/**
	 * Set value of isHTML
	 * @param ishtml
	 */
	public final void setisHTML(java.lang.Boolean ishtml)
	{
		setisHTML(getContext(), ishtml);
	}

	/**
	 * Set value of isHTML
	 * @param context
	 * @param ishtml
	 */
	public final void setisHTML(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean ishtml)
	{
		getMendixObject().setValue(context, MemberNames.isHTML.toString(), ishtml);
	}

	/**
	 * @return value of hasAttachments
	 */
	public final java.lang.Boolean gethasAttachments()
	{
		return gethasAttachments(getContext());
	}

	/**
	 * @param context
	 * @return value of hasAttachments
	 */
	public final java.lang.Boolean gethasAttachments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.hasAttachments.toString());
	}

	/**
	 * Set value of hasAttachments
	 * @param hasattachments
	 */
	public final void sethasAttachments(java.lang.Boolean hasattachments)
	{
		sethasAttachments(getContext(), hasattachments);
	}

	/**
	 * Set value of hasAttachments
	 * @param context
	 * @param hasattachments
	 */
	public final void sethasAttachments(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hasattachments)
	{
		getMendixObject().setValue(context, MemberNames.hasAttachments.toString(), hasattachments);
	}

	/**
	 * @return value of AttachmentAmount
	 */
	public final java.lang.Integer getAttachmentAmount()
	{
		return getAttachmentAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of AttachmentAmount
	 */
	public final java.lang.Integer getAttachmentAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.AttachmentAmount.toString());
	}

	/**
	 * Set value of AttachmentAmount
	 * @param attachmentamount
	 */
	public final void setAttachmentAmount(java.lang.Integer attachmentamount)
	{
		setAttachmentAmount(getContext(), attachmentamount);
	}

	/**
	 * Set value of AttachmentAmount
	 * @param context
	 * @param attachmentamount
	 */
	public final void setAttachmentAmount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer attachmentamount)
	{
		getMendixObject().setValue(context, MemberNames.AttachmentAmount.toString(), attachmentamount);
	}

	/**
	 * @return value of Size
	 */
	public final java.lang.Integer getSize()
	{
		return getSize(getContext());
	}

	/**
	 * @param context
	 * @return value of Size
	 */
	public final java.lang.Integer getSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Size.toString());
	}

	/**
	 * Set value of Size
	 * @param size
	 */
	public final void setSize(java.lang.Integer size)
	{
		setSize(getContext(), size);
	}

	/**
	 * Set value of Size
	 * @param context
	 * @param size
	 */
	public final void setSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer size)
	{
		getMendixObject().setValue(context, MemberNames.Size.toString(), size);
	}

	/**
	 * @return value of EmailMessage_EmailAccount
	 */
	public final imap_pop3_email.proxies.EmailAccount getEmailMessage_EmailAccount() throws com.mendix.core.CoreException
	{
		return getEmailMessage_EmailAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailMessage_EmailAccount
	 */
	public final imap_pop3_email.proxies.EmailAccount getEmailMessage_EmailAccount(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		imap_pop3_email.proxies.EmailAccount result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EmailMessage_EmailAccount.toString());
		if (identifier != null)
			result = imap_pop3_email.proxies.EmailAccount.load(context, identifier);
		return result;
	}

	/**
	 * Set value of EmailMessage_EmailAccount
	 * @param emailmessage_emailaccount
	 */
	public final void setEmailMessage_EmailAccount(imap_pop3_email.proxies.EmailAccount emailmessage_emailaccount)
	{
		setEmailMessage_EmailAccount(getContext(), emailmessage_emailaccount);
	}

	/**
	 * Set value of EmailMessage_EmailAccount
	 * @param context
	 * @param emailmessage_emailaccount
	 */
	public final void setEmailMessage_EmailAccount(com.mendix.systemwideinterfaces.core.IContext context, imap_pop3_email.proxies.EmailAccount emailmessage_emailaccount)
	{
		if (emailmessage_emailaccount == null)
			getMendixObject().setValue(context, MemberNames.EmailMessage_EmailAccount.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.EmailMessage_EmailAccount.toString(), emailmessage_emailaccount.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return emailMessageMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final imap_pop3_email.proxies.EmailMessage that = (imap_pop3_email.proxies.EmailMessage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "IMAP_POP3_email.EmailMessage";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
