// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package imap_pop3_email.proxies;

public enum MessageHandling
{
	NoHandling(new java.lang.String[][] { new java.lang.String[] { "nl_NL", "Geen actie uitvoeren" }, new java.lang.String[] { "en_ZA", "Nothing" }, new java.lang.String[] { "en_GB", "Nothing" }, new java.lang.String[] { "en_US", "None" } }),
	DeleteMessage(new java.lang.String[][] { new java.lang.String[] { "nl_NL", "Verwijderen van berichten" }, new java.lang.String[] { "en_ZA", "Delete retreived messages" }, new java.lang.String[] { "en_GB", "Delete retreived messages" }, new java.lang.String[] { "en_US", "Remove original emails from server" } }),
	MoveMessage(new java.lang.String[][] { new java.lang.String[] { "nl_NL", "Bericht verplaatsen" }, new java.lang.String[] { "en_ZA", "Move retreived messages to other folder" }, new java.lang.String[] { "en_GB", "Move retreived messages to other folder" }, new java.lang.String[] { "en_US", "Move emails on server to another (existing) folder" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private MessageHandling(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
